services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: python src/gossip/main.py
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: python src/gossip/app.py
    ports:
      - "5000:5000"
  qdrant:
    image: qdrant/qdrant:v1.0.3
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
